/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import static projetjava.InterfacePremiere.LSTDossMed;

/**
 *
 * @author WissemPC
 */
public class DonneesPers extends javax.swing.JInternalFrame {

    /**
     * Creates new form NvDossierMedical
     */
    public DonneesPers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genre = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ref = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        DN = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        Prenom = new javax.swing.JTextField();
        HomG = new javax.swing.JRadioButton();
        FemG = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        ErrRef = new javax.swing.JLabel();
        ErrNom = new javax.swing.JLabel();
        ErrPrenom = new javax.swing.JLabel();
        ErrDN = new javax.swing.JLabel();
        ErrGenre = new javax.swing.JLabel();
        ErrTel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Aff = new javax.swing.JButton();
        ErrREF = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Affichage Donnees Personnels");
        setName(""); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Reference Dossier*");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Date De Naissance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Genre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Telephone");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        Ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefActionPerformed(evt);
            }
        });
        getContentPane().add(Ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 24, 100, -1));

        Nom.setEnabled(false);
        getContentPane().add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 57, 100, -1));

        DN.setEnabled(false);
        getContentPane().add(DN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, -1));

        Tel.setEnabled(false);
        getContentPane().add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 100, -1));

        Prenom.setEnabled(false);
        getContentPane().add(Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 97, 100, -1));

        Genre.add(HomG);
        HomG.setText("Homme");
        HomG.setEnabled(false);
        HomG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomGActionPerformed(evt);
            }
        });
        getContentPane().add(HomG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        Genre.add(FemG);
        FemG.setText("Femme");
        FemG.setEnabled(false);
        getContentPane().add(FemG, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jButton3.setText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        ErrRef.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        ErrNom.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 57, -1, -1));

        ErrPrenom.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 97, -1, -1));

        ErrDN.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 137, -1, -1));

        ErrGenre.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 193, -1, -1));

        ErrTel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 239, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("*Obligatoire");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        Aff.setText("Afficher");
        Aff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffActionPerformed(evt);
            }
        });
        getContentPane().add(Aff, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        ErrREF.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrREF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/nvdc.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffActionPerformed
       DossierMedical h = new DossierMedical();     //button valider
       boolean empty=false;
      if(Ref.getText().equals(""))              //Controle de Saisie (Il peut y avoir des lettres) mais ne peut pas depasser 4 caracteres et doit exister dans le HashMap
        {
            ErrREF.setText("saisir Reference");         
          
            
        }
        else
         if ((Ref.getText()).length() != 4)  
            ErrREF.setText("Reference Doit avoir 4 caracteres ");
            else
             if (LSTDossMed.containsKey(Ref.getText())==false) 
            
            ErrRef.setText("Il n'y a pas de dossier médicale pour cette reference   ");
        else
        {    ErrRef.setText("");
                empty=true;}
         
      if (empty)                                //Afficher le dossier medical selon le reference (Key of the hashmap) 
      {h = LSTDossMed.get(Ref.getText()) ;
       Nom.setText(h.getNom());
       Prenom.setText(h.getPrenom());
       Tel.setText(Long.toString(h.getTelephone()));
       if ("Femme".equals(h.getGenre()))
           FemG.setSelected(true);
       else HomG.setSelected(true);
       DN.setText(h.getJDN()+"/"+h.getMDN()+"/"+h.getADN());}
    }//GEN-LAST:event_AffActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
setDefaultCloseOperation(NvDossierMedical.DISPOSE_ON_CLOSE);                //Quitter Interface
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void HomGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomGActionPerformed

    private void RefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aff;
    private javax.swing.JTextField DN;
    private javax.swing.JLabel ErrDN;
    private javax.swing.JLabel ErrGenre;
    private javax.swing.JLabel ErrNom;
    private javax.swing.JLabel ErrPrenom;
    private javax.swing.JLabel ErrREF;
    private javax.swing.JLabel ErrRef;
    private javax.swing.JLabel ErrTel;
    private javax.swing.JRadioButton FemG;
    private javax.swing.ButtonGroup Genre;
    private javax.swing.JRadioButton HomG;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Prenom;
    private javax.swing.JTextField Ref;
    private javax.swing.JTextField Tel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
