/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

;

import static projetjava.InterfacePremiere.LSTDossMed;

/**
 *
 * @author WissemPC
 */
public class HistCon extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistCon
     */
    public HistCon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        g = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        Refh = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ErrREF = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Afficher Historique");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Reference");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        g.setColumns(20);
        g.setRows(5);
        g.setEnabled(false);
        jScrollPane1.setViewportView(g);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 440, 430));

        jButton1.setText("Afficher Historique");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));
        getContentPane().add(Refh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 100, -1));

        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Historique des consultations");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 20));

        ErrREF.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrREF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/aqw.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  boolean empty=false;
      if(Refh.getText().equals(""))//Controle de Saisie sur la Reference (Doit Avoir un max de 4 caracteres et exister comme Key d'un Dossier Medical dans HashMap)
        {
            ErrREF.setText("saisir Reference"); 
          
            
        }
        else
         if ((Refh.getText()).length() != 4)  
            ErrREF.setText("Reference Doit avoir 4 caracteres ");
            else
         if (LSTDossMed.containsKey(Refh.getText())==false) 
            
            ErrREF.setText("Il n'y a pas de dossier médicale pour cette reference   ");
        else
        {    ErrREF.setText("");
                empty=true;}
      if (empty)    //Si tout est bon,on fait un nouveau Dossier Medical et on lui donne un dossier medical selon une reference et puis on l'affiche 
      {DossierMedical m = new DossierMedical() ;
       m=LSTDossMed.get(Refh.getText());
       g.setText(m.toString());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
setDefaultCloseOperation(NvConsultation.DISPOSE_ON_CLOSE); //Quitter
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrREF;
    private javax.swing.JTextField Refh;
    private javax.swing.JTextArea g;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
