/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static projetjava.InterfacePremiere.LSTDossMed;



/**
 *
 * @author WissemPC
 */
public class NvDossierMedical extends javax.swing.JInternalFrame {

    /**
     * Creates new form NvDossierMedical
     */
    public NvDossierMedical() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genre = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        hh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ref = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        Prenom = new javax.swing.JTextField();
        HomG = new javax.swing.JRadioButton();
        FemG = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ErrRef = new javax.swing.JLabel();
        ErrNom = new javax.swing.JLabel();
        ErrPrenom = new javax.swing.JLabel();
        ErrDN = new javax.swing.JLabel();
        ErrGenre = new javax.swing.JLabel();
        ErrTel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JD = new javax.swing.JComboBox<>();
        MD = new javax.swing.JComboBox<>();
        AD = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADEM\\Downloads\\azerty1.jpg")); // NOI18N
        jLabel10.setText("jLabel10");

        hh.setText("jLabel10");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nouveau Dossier Medical");
        setName(""); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Reference Dossier*");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nom*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Date De Naissance*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Genre*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 186, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Telephone*");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 242, -1, -1));
        getContentPane().add(Ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 100, -1));
        getContentPane().add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 100, -1));

        Tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelKeyPressed(evt);
            }
        });
        getContentPane().add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 239, 100, -1));
        getContentPane().add(Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, -1));

        Genre.add(HomG);
        HomG.setText("Homme");
        getContentPane().add(HomG, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 168, -1, -1));

        Genre.add(FemG);
        FemG.setText("Femme");
        getContentPane().add(FemG, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 202, -1, -1));

        jButton1.setText("Envoyer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jButton2.setText("Vider");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jButton3.setText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        ErrRef.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        ErrNom.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        ErrPrenom.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        ErrDN.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        ErrGenre.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        ErrTel.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabel7.setText("*Obligatoire");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        JD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jour", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(JD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        MD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mois", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(MD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        AD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Annee", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        getContentPane().add(AD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel8.setText("/");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel9.setText("/");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/azertyu.jpeg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public boolean verifnum (String S)
{ boolean t=true;                                            /* La fonction verifnum verifie si une chaine est constitué par des chiffres 
                                                               ou non si oui retourne true sinon retourna false */
int i=0;
    while ((i<S.length()) && (t))
    {  if ((S.charAt(i) <'0') || (S.charAt(i)>'9')) 
        t=false;
    else i++;}
    return t;}
   
   boolean alphabetique(String ch)
    {   boolean alp=true;
       int i=0;
       while ( (i<ch.length()) && (alp==true))
       { if ( ( (ch.charAt(i)>'z') || (ch.charAt(i)<'a') ) &&  ((ch.charAt(i)<'A') || (ch.charAt(i)>'Z'))) 
       {alp=false;}
       else i++;}
       
       return alp;
   }
   
public boolean inftr (int in)                                         /* La fonction inftr prend un entier en parametre et verifie si ce numero correspond 
                                                                        au mois qui contient des jours inferieur a 31 ou non si oui retourne true sinon false  */
{
    if (in==4 || in==6 || in==9 || in==11 || in==2)
        return true ;
    else return false ;
}
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
       int vid=0 ;
     boolean empty =false ;
      if(Ref.getText().equals(""))                                   /*Demande a l'utilisateur de saisir la reference s'il laisse la zone text vide
                                                                      */
        {                                                         
            ErrRef.setText("saisir Reference");
          empty=false;
            
        }
        else
        { if ((Ref.getText()).length() != 4)  
        {ErrRef.setText("Reference Doit avoir 4 caracteres ");empty=false;} /*Demande a l'utilisateur de resaisir la reference si le reference depasee 4 caractéres */
        else
        {    ErrRef.setText("");                           /* si tous les conditions sont verifier ne rien afficher comme erreur */
                empty=true;}}
      if (empty==false)
          vid++;
      
      if(Nom.getText().equals(""))                    /* Demande a l'utilisateur de saisir son nom s'il laisse la zone vide */
        {
            ErrNom.setText("saisir Nom");
            empty=false;
            
        }
      else 
      if (alphabetique(Nom.getText())==false ){
          ErrNom.setText("vous avez tapez des chiffres dans votre nom ");   /* Demande a l'utilisateur de saisir son nom s'il tape un chiffre dans son nom  */
              } 
        else
     
        {    ErrNom.setText("");                             
                empty=true;}
                                                                       /* Dans chaque controle la variable vid initialisé a 0  va prendre 1 de plus s'il ya une condition non verifié */
      if (empty==false)
          vid++;
      
      if(Prenom.getText().equals(""))                     /* Demande a l'utilisateur de saisir son Prenom s'il laisse la zone vide */
        {
            ErrPrenom.setText("saisir Prenom");
          empty=false;
            
        }
      else if (alphabetique(Prenom.getText())==false ) {
      ErrPrenom.setText("vous avez tapez des chiffres dans votre Prenom ");}     /* Demande a l'utilisateur de saisir son Prenom s'il tape un chiffre dans son nom  */
        else
     
        {    ErrPrenom.setText("");
                empty=true;}
      
      if (empty==false)
          vid++;
      
      if(Tel.getText().equals(""))                         /* Demande a l'utilisateur de saisir son telephone s'il laisse la zone vide */
        {ErrTel.setText("saisir Telephone");empty=false;}
        else if ((Tel.getText()).length() != 8)  
        {ErrTel.setText("Telephone doit avoir 8 chiffres ");empty=false;}   /* Demande a l'utilisateur de verifier son num telephone s'il depasse 8 chiffres ou moins  */
        else if (verifnum(Tel.getText())==false)
        {ErrTel.setText("Telephone doit etre un nombre ");empty=false;}   /* Demande a l'utilisateur de verifier son num si son numero contient des lettres  */
        else 
        {    ErrTel.setText("");
                empty=true;}
      
      if (empty==false)
          vid++;
      
       if ((!FemG.isSelected()) && (!HomG.isSelected()))
       {ErrGenre.setText("Veuillez Choisir Votre Genre");empty=false;}   /* demande a l'utilisateur de choisir son genre s'il laisse le  radio box non coché */
       else 
       {ErrGenre.setText("");
       empty=true;}
       
       if (empty==false)
          vid++;
       
       if ((JD.getSelectedIndex()==0) || (MD.getSelectedIndex()==0) || (AD.getSelectedIndex()==0))
        {   ErrDN.setText("Choisir Date");
            empty=false;                         /*Demande a l'utilisateur de choisir la date s'il laisse le jours ou le mois ou l 'annee non choisi */
    }                    
       
       else 
            if (inftr(MD.getSelectedIndex())==true) 
            {                                          /* Demande a l'utilisateur de verifier la date Si le  mois choisi est égale 2 et le jours est superieur a 29  */
            if (MD.getSelectedIndex()==2)
                { if (JD.getSelectedIndex()>29)
                {ErrDN.setText("Choisir jour inferieur a 29 ou mois different"); 
                         empty=false;}//erreur
                else 
                {ErrDN.setText("");
       empty=true;}
                }
            else
            {        if (JD.getSelectedIndex()>30)
            {ErrDN.setText("Choisir jour inferieur a 31 ou mois different ");
                                                 /* Demande a l'utilisateur de verifier la date Si le  mois choisi ne contient pas 31 jours  */
                    empty=false;}
            else 
            {ErrDN.setText("");
       empty=true;}
               }    
            }
       else
       {ErrDN.setText("");
       empty=true;}

        
        if (empty==false)
          vid++;
     
        
         if (vid ==0)      /* vid=0 donc tous les conditions sont verifiés pas d'erruer */
         { 
              if  (LSTDossMed.get(Ref.getText())!=null)           /* Si la reference tapez existe deja l'application va afficher un message   */
                                                                   /* LSTDossMed le nom du hashmap dans laquelle on a stocké les dossiers medicaux  */
                {JOptionPane.showMessageDialog(null, "Ce Dossier Medical existe deja","Fichier Existant", 0);}
        else
         {   DossierMedical d = new DossierMedical() ;       /* Si le refrenece n'existe pas on va creer un  nouveau  dossier medicale  dans lequel 
                                                              on va stocker le telephone , la reference le genre le nom le prenom et la date de naissance 
                                                              tapez par l'utilisateur .*/
         
            d.setTelephone(Long.parseLong(Tel.getText()));
            d.setRef(Ref.getText());
            if (HomG.isSelected())
            d.setGenre("Homme");
            else 
            d.setGenre("Femme");
            d.setNom(Nom.getText());
            d.setPrenom(Prenom.getText());
            d.setJDN(JD.getSelectedIndex());
            d.setADN(AD.getSelectedIndex()+1919);
            d.setMDN(MD.getSelectedIndex());
            ArrayList <Consultation> x = new ArrayList() ;    /* Creation d'une  consultaion  */
            d.setCon(x);                                   /* stockage du consultation dans le tableau des consultations dans le dossier medicale  */
             LSTDossMed.put(Ref.getText(), d) ;        /* stochage du dossier medicale dans le Hashmap par reference */
            JOptionPane.showMessageDialog(null, "Ajout Succes" ,"Fichier Ajoute", 1); } }   /*affiche que le dossier etait bien ajoutée  */
                                            
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
setDefaultCloseOperation(NvDossierMedical.DISPOSE_ON_CLOSE);
setVisible(false);
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        { Ref.setText("");
  Nom.setText("");
  Prenom.setText("");
  Tel.setText("");              /* vider tous les cases on cliquant sur  vider */
  Genre.clearSelection();
  JD.setSelectedIndex(0);
  MD.setSelectedIndex(0);
  AD.setSelectedIndex(0);
    }                                        

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AD;
    private javax.swing.JLabel ErrDN;
    private javax.swing.JLabel ErrGenre;
    private javax.swing.JLabel ErrNom;
    private javax.swing.JLabel ErrPrenom;
    private javax.swing.JLabel ErrRef;
    private javax.swing.JLabel ErrTel;
    private javax.swing.JRadioButton FemG;
    private javax.swing.ButtonGroup Genre;
    private javax.swing.JRadioButton HomG;
    private javax.swing.JComboBox<String> JD;
    private javax.swing.JComboBox<String> MD;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Prenom;
    private javax.swing.JTextField Ref;
    private javax.swing.JTextField Tel;
    private javax.swing.JLabel hh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
